### ISSUE TITLE
Error of undefined this.dom.play in stream load metadata funciton

### ISSUE THREAD

**Issue by dano1234** [vanevery/p5.simplesimplepeer#10]
https://www.hypercinema.org/OSC/Convene/p5LiveMedia/liveMedia.html
https://github.com/dano1234/OSC21/tree/master/Convene/p5LiveMedia

Scroll zoom out and scroll down and all the video elements are below the threejs dom element.

liveMedia.js:39 V
p5livemedia.js:340 Uncaught TypeError: Cannot read property 'play' of undefined
    at HTMLVideoElement.domElement.onloadedmetadata (p5livemedia.js:340)

**Comment by vanevery** [comment]
Fixed in commit https://github.com/vanevery/p5LiveMedia/commit/c997bfc92c1c1614a0d44e43debf44d6d8320b0f
