### ISSUE TITLE
Change name to peer5?

### ISSUE THREAD

**Issue by vanevery** [vanevery/p5.simplesimplepeer#6]
p5.live is the winner!

**Comment by MathuraMG** [comment]
@vanevery that's perfect !

**Comment by vanevery** [comment]
Should really have done a google search before changing the name.  p5live is being use by a p5 live coding environment: https://github.com/ffd8/P5LIVE

**Comment by vanevery** [comment]
Other ideas:
p5LiveWeb
p5LiveAudioVideoData
p5LiveMedia <--  I kind of like this

**Comment by nopivnick** [comment]
looks like I should have weighed in 5 hours ago but fwiw, I've always prefered the 'p5 dot' prefix (p5.liveMedia).

so does the emphasis on Live*Media* (also [this](https://github.com/vanevery/p5LiveMedia/issues/1#issuecomment-724111517) comment) mean exchanging non-audio / non-video data types between peers is still best handled using @bmoren 's [p5.localmessage](https://github.com/bmoren/p5.localmessage) library?

**Comment by craigprotzel** [comment]
My vote would be for **p5.liveMedia**

**Comment by ffd8** [comment]
just found this while searching 'p5 webrtc' to research using webrtc audio stream/share feeds within the p5.sound analysis (peer 2 peer vj'ing.. ahem, while COCODING in P5LIVE) – this lib looks amazing! slowly digging through many great examples. 

naming things is sooo hard (and fun..?) – perhaps it's already settled.. but 2¢ ideas: `p5.peer` / `p5.peers` / `p5.webrtc` – but it's all semantics and `p5LiveMedia` makes lots of sense in terms of content shared. thanks for making this!

**Comment by vanevery** [comment]
@nopivnick sorry, I think I missed your question about p5.localmessage previously.  I am not sure how that works but p5LiveMedia can definitely be used to share peer to peer messages.

@ffd8 WOW!  That's a lot of interesting things happening all at once!  Happy to help getting p5.sound working with on the audio that is sent/received through p5LiveMedia.  I went with p5LiveMedia instead of references to peer and webrtc as those are pretty much for folks in the know and I wanted to make it more accessible sounding ;-)

**Comment by bmoren** [comment]
> looks like I should have weighed in 5 hours ago but fwiw, I've always prefered the 'p5 dot' prefix (p5.liveMedia).
> 
> so does the emphasis on Live_Media_ (also [this](https://github.com/vanevery/p5LiveMedia/issues/1#issuecomment-724111517) comment) mean exchanging non-audio / non-video data types between peers is still best handled using @bmoren 's [p5.localmessage](https://github.com/bmoren/p5.localmessage) library?

Hey, chiming in here, just to say that these libraries work with two totally different technologies, livemedia being based on webRTC so peer to peer and localmessage around a serviceworker, so it's **local only**. 

my understanding is that livemedia can send messages from one machine to another – the peer to peer part. Whereas, local message can only send messages on the **same** machine – local. 

I suppose it's totally possible to set up livemedia to send localmessages as well, but at least for me one of the benefits of local message is that it does not require any server setup, everything still runs in the client, so it's really easy to implement.

I'm not super familiar with livemedia's setup (or WebRTC, so correct me if I'm wrong!), but it looks like @vanevery has done a lot of nice work to hide the server stuff to make it as friendly as possible to get up and running quickly.

I would suspect either route would work fine for a local application, but if you're trying to get one machine to talk to another machine, then livemedia is the ticket!

Side note about localmessage's initialization motivation: I had a student who needed to have one sketch as a controller input and another sketch as a display. (A kiosk prompt to type into, and a giant projected head that would talk back to you!) On old macs you could do this by having a really wide window and going into Full Screen mode and stretch the window across 2 monitors. In newer Mac OS versions, this is no longer easily done, so the sketch needed to be broken into 2 and full screened in the 2 separate displays.
