### ISSUE TITLE
Getting Errorr that it can't call "play" of undefined on  connect but it does no harm

### ISSUE THREAD

**Issue by dano1234** [vanevery/p5.simplesimplepeer#7]
I think I get this on all examples?

p5livemedia.js:338 Uncaught TypeError: Cannot read property 'play' of undefined
    at HTMLVideoElement.domElement.onloadedmetadata (p5livemedia.js:338)
domElement.onloadedmetadata @ p5livemedia.js:338
VM30 about:srcdoc:40 Uncaught TypeError: Cannot read property 'split' of undefined
    at window.onerror (VM30 about:srcdoc:40)

**Comment by dano1234** [comment]
https://editor.p5js.org/dano/sketches/pAYsVgG_r
Can't get disconnect to work, get this error instead

Error: id is not defined
    at r.<anonymous> (p5livemedia.js:129)
    at r.emit (socket.io.js:6)
    at r.onevent (socket.io.js:8)
    at r.onpacket (socket.io.js:8)
    at r.<anonymous> (socket.io.js:8)
    at r.emit (socket.io.js:6)
    at r.ondecoded (socket.io.js:6)
    at a.<anonymous> (socket.io.js:8)
    at a.r.emit (socket.io.js:6)
    at a.add (socket.io.js:6)
(anonymous) @ p5livemedia.js:129
r.emit @ socket.io.js:6
r.onevent @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
r.onData @ socket.io.js:7
ws.onmessage @ socket.io.js:8
about:srcdoc:40 Uncaught TypeError: Cannot read property 'split' of undefined
    at window.onerror (about:srcdoc:40)
window.onerror @ about:srcdoc:40
error (async)
(anonymous) @ about:srcdoc:35
simplepeer.min.js:6 Uncaught RTCError: Transport channel closed
n.emit @ simplepeer.min.js:6
_destroy @ simplepeer.min.js:6
destroy @ simplepeer.min.js:6
_channel.onerror @ simplepeer.min.js:6
error (async)
_setupData @ simplepeer.min.js:6
p @ simplepeer.min.js:6
SimplePeerWrapper @ p5livemedia.js:283
(anonymous) @ p5livemedia.js:140
r.emit @ socket.io.js:6
r.onevent @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
n @ socket.io.js:7
e.decodePayload @ socket.io.js:7
r.onData @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
i.onData @ socket.io.js:7
i.onLoad @ socket.io.js:7
hasXDR.e.onreadystatechange @ socket.io.js:7
XMLHttpRequest.send (async)
i.create @ socket.io.js:7
i @ socket.io.js:7
o.request @ socket.io.js:7
o.doPoll @ socket.io.js:7
r.poll @ socket.io.js:7
r.onData @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
i.onData @ socket.io.js:7
i.onLoad @ socket.io.js:7
hasXDR.e.onreadystatechange @ socket.io.js:7
XMLHttpRequest.send (async)
i.create @ socket.io.js:7
i @ socket.io.js:7
o.request @ socket.io.js:7
o.doPoll @ socket.io.js:7
r.poll @ socket.io.js:7
r.doOpen @ socket.io.js:7
r.open @ socket.io.js:7
r.open @ socket.io.js:7
r @ socket.io.js:6
r @ socket.io.js:6
r.open.r.connect @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
p5LiveMedia @ p5livemedia.js:84
gotMineConnectOthers @ about:srcdoc:94
(anonymous) @ p5.js:59507

**Comment by vanevery** [comment]
Disconnect errors are fixed.  I believe the other errors you reported are fixed as well, I don't see them show up in your example any longer.
