### ISSUE TITLE
Not hiding new video elements with additional stream

### ISSUE THREAD

**Issue by dano1234** [vanevery/p5.simplesimplepeer#9]
https://www.hypercinema.org/OSC/Convene/p5LiveMedia/liveMedia.html
https://github.com/dano1234/OSC21/tree/master/Convene/p5LiveMedia

Scroll zoom out and scroll down and all the video elements are below the threejs dom element.

**Comment by vanevery** [comment]
These should be hidden on the implementation side:

```
function setup() {
  createCanvas(400,400);

  myVideo = createCapture(VIDEO, 
    function(stream) {
	let p5lm = new p5LiveMedia(this, "CAPTURE", stream, "EXAMPLE")
  	p5lm.on('stream', gotStream);
    }
  );
}

function gotStream(stream) {
stream.hide();
}

```
